### ISSUE TITLE
Final checklist

### ISSUE THREAD

**Issue by gvegayon** [mthroolin/phs7045midterm#4]
## R package component

- [x] Add a new function/feature to the R package using parallel computing or `Rcpp` (a must.)
- [x] The package should have a `README.md` file with a brief description of the package.
- [ ] The package should pass `R CMD check`s using macOS, Ubuntu, and Windows for the R release and development versions (x6 `R CMD check`s). Notes are OK, but warnings are not (recall the `usethis::use_github_action...` function). 
- [ ] The package should pass the `R CMD check` on Ubuntu using the R release version with the option [`--as-cran`](https://cran.r-project.org/web/packages/submission_checklist.html) (more strict `R CMD check`.)
- [x] The package should have a vignette that illustrates the use of the functions in the package.

## Presentation component

- [ ] The time allocation will be 7 minutes (5/100 points of penalty per extra minute).
- [ ] Presentation should be clear.
- [ ] It Should be presented with slides using quarto.
- [ ] Review of the problem which highlights the issue or “why” the problem needs solving (may consider including visuals to highlight the issue; ~2 slides)
- [ ] Overview of the package until the midterm (~1 slide)
- [ ] The new feature of the coding solution (other than the R package itself; ~ 1 slide each)
- [ ] Provide a single example highlighting the package (~1-3 slides).

attn @chipmanj

**Comment by gvegayon** [comment]
@mthroolin, it seems that the runner using macos-12 is deprecated. You can set up python in your GitHub actions workflow using this: https://github.com/marketplace/actions/setup-python. @sima-njf, you should use that too for setting up Python. LMK if you guys need help.

**Comment by mthroolin** [comment]
> @mthroolin, it seems that the runner using macos-12 is deprecated. You can set up python in your GitHub actions workflow using this: https://github.com/marketplace/actions/setup-python. @sima-njf, you should use that too for setting up Python. LMK if you guys need help.

@gvegayon I tried depreciating to Python 3.11 and Python 3.12. But still having issues.

**Comment by gvegayon** [comment]
I see that. Don't worry about it. We can sort that out later.

attn @chipmanj
